language: python
python:
    - "2.7"
install:
    - pip install --upgrade pip setuptools wheel
    - pip install numpy scipy
    - pip install weave
    - sudo apt-get install -qq libhdf5-serial-dev
    - pip install h5py
    - pip install healpy
    - pip install ephem
    - python setup.py install

script:
    - python test/check_maps.py
