language: python
python:
    - "2.7"
install:
    - apt-get install -qq libhdf5-serial-dev
    - pip install h5py
    - pip install healpy
    - pip install ephem
    - pip install pyslalib

script:
    - python test/check_maps.py
