language: python
python:
    - "2.7"
install:
    - pip install --upgrade pip setuptools wheel
    - pip install --only-binary=numpy,scipy numpy scipy
    - sudo apt-get install -qq libhdf5-serial-dev
    - pip install h5py
    - pip install healpy
    - pip install ephem

script:
    - python test/check_maps.py
